baseURL = 'https://example.com/'
languageCode = 'en-us'
title = "An example fanfiction site."
theme = 'nostyleplease'
[taxonomies]
    tag = "tags"
    category = "categories"
    fandom = "fandoms"
    source = "sources"
